name: CD / Deploy / Production

on: 
  push:
    tags:        
      - '**'  
  workflow_dispatch:
    
      
jobs:
  build-image:
    runs-on: lil-server
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build Docker Image...
        run: docker build -t resume-${{github.ref_name}} .

  run-container:
    runs-on: lil-server
    needs: [ build-image ]
    steps:
      - name: Run Docker Container...
        run: docker run --name=resume-container-${{github.ref_name}} -p 3000:3000 resume-${{github.ref_name}}


